# Generated by Django 2.0.6 on 2018-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('color_or_pattern', models.CharField(max_length=100)),
                ('favourite_prey', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('venomous', models.CharField(max_length=4)),
                ('imagePath', models.CharField(max_length=200)),
            ],
        ),
    ]
